site_name: BELLA
site_url: https://gabriele-marino.github.io/BELLA/
docs_dir: doc
theme:
  name: cinder
nav:
  - Introduction: introduction.md
  - Installation: installation.md
  - Components: components.md
  - Usage: usage.md
  - Cite: cite.md
