site_name: BELLA
site_url: https://gabriele-marino.github.io/BELLA/
docs_dir: doc
theme:
  name: cinder
nav:
  - Installation: installation.md
  - Tutorials:
      - Overview: tutorials/index.md
      - FBD example: tutorials/fbd.md
  - Components: components.md
  - Cite: cite.md
